version: '3.8'

services:
  app:
    build: webapp
    image: camper484/autvarunapp
    environment:
      - DISPLAY=unix$DISPLAY
    expose:
      - "8000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix


  git:
    build: git
    image: camper484/autvarungit
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    expose:
      - "8080"
    depends_on:
      - app
