version: '3.8'

services:
  app:
    build: webapp
    image: camper484/autvarunapp
    environment:
      - DISPLAY=unix$DISPLAY
    expose:
      - "8000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix


  git:
    build: git
    image: camper484/autvarungit
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    expose:
      - "8090"
    depends_on:
      - app

  orange:
    image: camper484/autvarunorange
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    expose:
      - "7075"
    depends_on:
      - app

  tensorflow:
    image: camper484/autvaruntensorflow
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    expose:
      - "7080"
    depends_on:
      - app

  spyder:
    image: camper484/autvarunspyderimg
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    expose:
      - "7085"
    depends_on:
      - app

  hadoopwrapper:
    image: camper484/autvarungit
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    expose:
      - "7090"
    depends_on:
      - app

  rstudio:
    build: rstudioimg
    image: camper484/autvarunrstudio
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    expose:
      - "8085"
    depends_on:
      - app

  markdown:
    image: camper484/autvarunmarkdown
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    expose:
      - "8050"
    depends_on:
      - app

  spark:
    image: camper484/autvarunsparkwrapper
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'

  spark-worker-1:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  spark-worker-2:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  sonar-scanner:
    image: camper484/autvarunqubewrapper
    entrypoint: python runner.py
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /scan
    links:
      - sonarqube
    stdin_open: true
    tty: true
    expose:
      - "8045"
    depends_on:
      - app
      - sonarqube

  sonarqube:
    image: newtmitch/sonar-server
    ports:
      - "9000:9000"
      - "9092:9092"
